apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-service
spec:
  selector:
    matchLabels:
      app: twitter-service
  replicas: 3
  template:
    metadata:
      labels:
        app: twitter-service
    spec:
      containers:
        - name: twitter-service
          image: bnasslahsen/devops-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://test-db-mysql.default.svc.cluster.local:3306/devops1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32087
  selector:
    app: twitter-service